accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signupview/', views.signup_view, name='signup-view'),
    path('class/', views.class_view, name='class-list'),
    path('class/<int:class_id>/detail/', views.class_detail_view, name='class-detail'),
    path('class/<int:class_pk>/add/', views.class_member_add_view, name='add-class-members'),
    path('class/<int:class_pk>/delete/', views.class_member_delete_view, name='delete-class-members'),
]

book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/', views.ListBookView.as_view(), name='list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name='detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name='create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update-book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review'),
    path('savebook/', views.savebook_list_view, name='list-savebook'),
    path('savebook/append/', views.savebook_append, name='append-savebook'),
    path('savebook/orderchange/', views.savebook_orderchange_view, name='orderchange-savebook'),
    path('savebook/delete/', views.bookorder_delete, name='delete-savebook'),
    path('like_for_book/', views.like_for_book, name='like_for_book'), 
]

bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django_mysql.models import ListCharField
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # 一つのユーザーはプロフィールを一つしか持てない
    save_book_id = ListCharField(
            models.CharField(max_length=100, null=True, blank=True),max_length=(6 * 11), null=True, blank=True)

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
# ↑sender(User)をsave()した時に↓（create_profile）が実行されるようになる（DjangoでUser登録した際は必ずその情報をsaveするように設定されているため、その際に実行させる）
def create_profile(sender, instance, created, **kwargs):
    if created:
        # -----↓Profileモデルを、userフィールドにinstance情報を積めながらcreate(新規作成)する
        Profile.objects.create(user=instance)
        # -----↑user...Profileで作成したuserフィールド
        # instance...saveしたデータ（新規作成した一人分のUser情報）が代入されてくる
    instance.profile.save()

class Class(models.Model):
    name = models.CharField("クラス名", max_length=100)
    members = models.ManyToManyField(User)
    def __str__(self):
        return str(self.name)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Class

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

# class AddClassMembersForm(forms.ModelForm):
#     class Meta:
#         model = Class
#         fields = ('', 'user_name')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import SignupForm

from .models import Profile, Class

from time import sleep

import sys
sys.path.append('../')
from book.models import Book

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('index')

def signup_view(request):
    # ----------↓POSTメソッドが返された場合（＝サインアップのアカウント作成ボタンが押された場合）↓----------
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        # -----↓正常な値が代入されていた時の分岐↓-----
        if form.is_valid():
            form.save() #データベース登録
            # user.refresh_from_db()
            # --↓formに入力された情報を受け取り↓--
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # --↓それをDjangoのデータベースに反映--
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
        # -----
    # ----------
    # ----------↓その他の場合（つまりGETメソッドが返された場合）↓----------
    else:
        form = UserCreationForm()
    # ----------↑その他の場合（つまりGETメソッドが返された場合）↑----------
    return render(request, 'accounts/signup.html', {'form': form})
    # ----------

# from django.db import transaction
# @transaction.atomic
# def create_user(request):
#     if request.method == 'POST':
#         user_form = UserCreationForm(request.POST)
#         if user_form.is_valid():
#             user = user_form.save()
#             user.refresh_from_db() 
#     else:
#         user_form = UserCreationForm()

#     return render(request, 'user_form.html', {
#         'user_form': user_form,
#     })


# def orderlist_view(request, pk):
#     object_list = Book.objects.all()
#     profile = Profile.objects.all() # prifileに全プロフィールデータが入る（できれば一人分のデータのみを取るようにしてスッキリさせたい？）
#     profile1 = Profile.objects.get(pk=pk) # profile1に一人分のプロフィールデータが入る
#     order_list = profile1.book_order # profile1の本の並び順を取得する
#     object_pk_list = []
#     for obj in object_list:
#         object_pk_list.append(obj.pk)
#     print(object_pk_list)
#     print(order_list)
#     # ----------↓並び替え確定のボタンが押されてリクエストが来た時の分岐↓----------
#     if (request.method == 'POST'):
#         sleep(5)
#         new_order = request.POST['submit'].split(",") # new_orderに並び替えた後のデータをリスト型で保管する
#         print(f"html側から受け取ったもの：{new_order}") # htmlから渡されたものを確認する
#         profile1.book_order = new_order # プロフィールのbook_orderに上書き
#         profile1.save() # 変更を保存
#         print(f"afterのlist：{profile1.book_order}") # profileテーブルの内容が上書きされているかを確認する
#         # -----↓変更したものはもう一度定義し直さないとhtml側には古い（変更前の）情報が渡ってしまう（いらないものもありそう？）↓-----
#         object_list = Book.objects.order_by()
#         profile = Profile.objects.all()
#         profile1 = Profile.objects.get(pk=pk)
#         order_list = profile[0].book_order
#         # -----↑変更したものはもう一度定義し直さないとhtml側には古い（変更前の）情報が渡ってしまう（いらないものもありそう？）↑-----
#     # ----------↑並び替え確定のボタンが押されてリクエストが来た時の分岐↑----------
#     context = {
#         "object_list": object_list,
#         "object_pk_list": object_pk_list,
#         "order_list": order_list,
#     }
#     return render(
#     request,
#     'accounts/orderlist.html',
#     context) 

def orderlist_view(request):
    object_list = Book.objects.all()
    profile1 = Profile.objects.get(pk=request.user.id) # profile1に一人分のプロフィールデータが入る
    order_list = profile1.save_book_id # profile1の本の並び順を取得する
    object_pk_list = []
    for obj in object_list:
        object_pk_list.append(obj.pk)
    print(f"全書籍のid:{object_pk_list}")
    print(f"ユーザーの並び変え順:{order_list}")
    # ----------↓設定されている順番に並び替える↓----------
    books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
    sorted_books = [books_dict[int(id)] for id in order_list] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
    print(f"並び替えられた書籍データ:{sorted_books}")
    # ----------↑設定されている順番に並び替える↑----------
    context = {
        "object_list": object_list,
        "object_pk_list": object_pk_list,
        "order_list": order_list,
        "sorted_books": sorted_books
    }
    return render(
    request,
    'accounts/orderlist.html',
    context) 

def orderchange_view(request):
    # ----------↓object_listに全書籍データを代入↓----------
    object_list = Book.objects.all()
    # ----------↓profile1にログインしているユーザーのプロフィール情報を代入↓----------
    profile1 = Profile.objects.get(pk=request.user.id) # profile1に一人分のプロフィールデータが入る
    # ----------↓profile1の本の並び順を取得する↓----------
    order_list = profile1.save_book_id
    object_pk_list = []
    for obj in object_list:
        object_pk_list.append(obj.pk)
    # print(f"全書籍のid(object_pk_list):{object_pk_list}")
    # print(f"ユーザーの並び変え順(order_list):{order_list}")
    # ----------↓設定されている順番に並び替える↓----------
    books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
    sorted_books_list = [books_dict[int(id)] for id in order_list] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
    # print(f"idとデータの辞書(book_dict):{books_dict}")
    print(f"並び替えられた書籍データ（sorted_books_list）:{sorted_books_list}")
    # ----------↑設定されている順番に並び替える↑----------
    # ----------↓並び替え確定のボタンが押されてリクエストが来た時の分岐↓----------
    if (request.method == 'POST'):
        new_order = request.POST['submit'].split(",") # new_orderに並び替えた後のデータをリスト型で保管する
        # print(f"html側から受け取ったもの：{new_order}") # htmlから渡されたものを確認する
        profile1.save_book_id = new_order # プロフィールのsave_book_idに上書き
        profile1.save() # 変更を保存
        print(f"並び替え後のlist：{profile1.save_book_id}") # profileテーブルの内容が上書きされているかを確認する
        return redirect('accounts:orderlist-book')
    # ----------↑並び替え確定のボタンが押されてリクエストが来た時の分岐↑----------
    # ----------↓並び替えするためにリクエストが来た時の分岐↓----------
    else:
        context = {
            "object_list": object_list, # 全書籍データ
            "object_pk_list": object_pk_list, # 全書籍データ（idのみ）
            "order_list": order_list, # ユーザーの並び替え順（idのみ）
            "books_dict": books_dict, # {id: その書籍データ}と、辞書型で全書籍データがある
            "sorted_books_list": sorted_books_list, # 並び替え順で書籍データが詰まっている（リスト型）
        }
        return render(
        request,
        'accounts/order_change.html',
        context)
    # ----------↑並び替えするためにリクエストが来た時の分岐↑----------

def bookorder_append(request):
    object_list = Book.objects.all()
    profile1 = Profile.objects.get(pk=request.user.id)
    # ----------↓obj_li_pkに全書籍のidを詰め込む↓----------
    obj_li_pk = []
    for obj in object_list:
        obj_li_pk.append(obj.id)
    # ----------↑obj_li_pkに全書籍のidを詰め込む↑----------
    # ----------↓obj_li_pkの中から、既に保存している書籍は削除する↓----------
    for item in profile1.save_book_id:
        obj_li_pk.remove(int(item))
    print(f'{profile1.user}の保存していない書籍番号:{obj_li_pk}')
    books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
    display_books_list = [books_dict[int(id)] for id in obj_li_pk] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
    context = {
        'object_list': object_list, # 全書籍データ
        'display_books_list': display_books_list, # 表示する書籍データがリスト形で詰まっている
    }
    return render(
        request,
        'accounts/bookorder_append.html',
        context
)

def bookorder_delete(request, book_id):
    profile1 = Profile.objects.get(pk = request.user.id)
    # ----------削除ボタンが押された分岐----------
    if request.method == 'POST':
        delete_book = request.POST['office']
        print(delete_book)
        # profile1.save_book_id.remove(str(book_id))
        # profile1.save()
        return redirect('accounts:orderlist-book')
    # ----------
    # ----------削除画面にアクセスする----------
    else:
        delete_book = Book.objects.get(pk = book_id)
        return render(request, 'accounts/bookorder_delete.html',
        {
            'delete_book': delete_book,
        })
# from .models import Question # 並び替える対象は『Question』
 
# question_ids = ['q40', 'q30', 'q20', 'q10'] # この順番に並び替えたい
 
# question_qs = Question.objects.filter(question_id__inquestion_ids) # Questionモデルから『question_ids』のみのIDを取得
# ↓ここから並べる↓
# questions_dict = dict([(question.question_id, question) for question in question_qs])　# [id: そのidのQuestionデータ]という形で辞書に収める
# sorted_questions = [questions_dict[id] for id in session_question_ids_list]

# import sys
# sys.path.append('../')
# from book.models import Book
# book_ids = [11, 12]
 
# book_qs = Book.objects.filter(Book.id in book_ids)
 
# books_dict = dict([(book.book_id, book) for book in book_qs])
# sorted_books = [books_dict[id] for id in books_dict]
# print(sorted_books)



# def orderlist_view(request, pk):
#     object_list = Book.objects.all()
#     profile = Profile.objects.all() #prifileに全プロフィールデータが入る（できれば一人分のデータのみを取るようにしてスッキリさせたい？）
#     profile1 = Profile.objects.get(pk=pk) #profile1に一人分のプロフィールデータが入る
#     order_list = profile1.book_order #profile1の本の並び順を取得する
#     #----------↓並び替え確定のボタンが押されてリクエストが来た時の分岐↓----------
#     if (request.method == 'POST'):
#         new_order = request.POST['submit'].split(",") #new_orderに並び替えた後のデータをリスト型で保管する
#         # print(f"html側から受け取ったもの：{new_order}") #htmlから渡されたものを確認する
#         profile1.book_order = new_order # プロフィールのbook_orderに上書き
#         profile1.save() # 変更を保存
#         print(f"afterのlist：{profile1.book_order}") # profileテーブルの内容が上書きされているかを確認する
#         # -----↓変更したものはもう一度定義し直さないとhtml側には古い（変更前の）情報が渡ってしまう（いらないものもありそう？）↓-----
#         object_list = Book.objects.order_by()
#         profile = Profile.objects.all()
#         profile1 = Profile.objects.get(pk=pk)
#         order_list = profile[0].book_order
#         # -----↑変更したものはもう一度定義し直さないとhtml側には古い（変更前の）情報が渡ってしまう（いらないものもありそう？）↑-----

accounts/templates/accounts/class_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ object.name }}のメンバー一覧{% endblock title %}
{% block h1 %}{{ object.name }}のメンバー一覧{% endblock h1 %}
{% block content %}
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            margin-top: 50px;
        }

        h1 {
            color: #28a745;
        }

        .card {
            background-color: #e9f5e9;
            border: 1px solid #28a745;
            border-radius: 5px;
        }

        .card-header {
            background-color: #28a745;
            color: #ffffff;
        }

        .card-body {
            color: #333333;
        }
    </style>
    <div class="container">
        <div class="d-flex justify-content-end mb-3">
            <a href="{% url 'accounts:add-class-members' object.pk %}" class="btn btn-success">メンバーを追加</a>
            <a href="{% url 'accounts:delete-class-members' object.pk %}" class="btn btn-danger">メンバーを削除</a>
        </div>
        <div class="card">
            <div class="card-header">
                {{ object.name }}
            </div>
            <div class="card-body">
                {% for member in object.members.all %}
                    <p>{{ member.username }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/class_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}クラス一覧{% endblock title %}
{% block h1 %}クラス一覧{% endblock %}
{% block content %}
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            margin-top: 50px;
        }

        h1 {
            color: #28a745;
        }

        table {
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>クラス名</th>
                    <th>学生数</th>
                </tr>
            </thead>
            <tbody>
                {% for class in object_list %}
                    <tr>
                        <td><a href="{% url 'accounts:class-detail' class.pk %}">{{ class.name }}</a></td>
                        <td>{{ class.members.all|length }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

accounts/templates/accounts/class_members.delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}メンバー追加{% endblock title %}
{% block h1 %}メンバー追加{% endblock %}
{% block content %}
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        h1 {
            color: #28a745;
        }
        .card {
            background-color: #ffffff;
            border: 1px solid #28a745;
            border-radius: 5px;
        }
        .card-header {
            background-color: #28a745;
            color: #ffffff;
        }

        .card-body {
            color: #333333;
        }
    </style>
    <div class="container">
        <div class="card">
            <div class="card-header">
                {{ class.name }}に参加済みのメンバー一覧
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for user in members_list %}
                        <div class="form-group">
                            <label for="member{{ user.id }}">
                                <input type="checkbox" id="member{{ user.id }}" name="members" value="{{ user.id }}"> {{ user.username }}
                            </label>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-danger">メンバーから削除する</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/class_members_add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}メンバー追加{% endblock title %}
{% block h1 %}メンバー追加{% endblock %}
{% block content %}
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        h1 {
            color: #28a745;
        }
        .card {
            background-color: #ffffff;
            border: 1px solid #28a745;
            border-radius: 5px;
        }
        .card-header {
            background-color: #28a745;
            color: #ffffff;
        }

        .card-body {
            color: #333333;
        }
    </style>
    <div class="container">
        <div class="card">
            <div class="card-header">
                {{ class.name }}に参加していないユーザー一覧
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for user in user_list %}
                        <div class="form-group">
                            <label for="member{{ user.id }}">
                                <input type="checkbox" id="member{{ user.id }}" name="members" value="{{ user.id }}"> {{ user.username }}
                            </label>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">メンバーを追加する</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/orderlist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}書籍一覧{% endblock title %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
<!-- <a href="{% url 'accounts:bookorder-append' %}" class="btn btn-primary">書籍を追加する</a>
<a href="{% url 'accounts:orderchange-book' %}" class="btn btn-primary">並び替える</a> -->
{% for book in sorted_books %}
<div class="p-4 m-4 bg-light border border-success rounded">
    <h2 class="text-success">{{ book.title }}</h2>
    {% if book.thumbnail %}
        <img src="{{ book.thumbnail.url }}" class="img-thumbnail" />
    {% endif %}
    <h6>カテゴリ：{{ book.category }}</h6>
    <div class="mt-3">
        <a href="{% url 'detail-book' book.pk %}" class="btn btn-primary">詳細</a>
        <a href="{% url 'accounts:bookorder-delete' book.pk %}" class="btn btn-primary">保存リストから削除</a>
    </div>
</div>
{% endfor %}

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}
{% block content %}
    <form action="", method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        <input type="text" name="username" class="form-control my-4" placeholder="ユーザーID">
        <input type="password" name="password1" class="form-control mt-4" placeholder="パスワード">
        <input type="password" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
        <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。</small>
        {% if form.errors %}
            <span class="mb-2 small text-danger d-block tezt-start">利用できないユーザーIDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
        {% endif %}
        <button type="submit" class="btn btn-success m-2">アカウント作成</button>
    </form>
{% endblock %}