accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signupview/', views.signup_view, name='signup-view'),
    path('class/', views.class_view, name='class-list'),
    path('class/<int:class_id>/detail/', views.class_detail_view, name='class-detail'),
    path('class/<int:class_pk>/add/', views.class_member_add_view, name='add-class-members'),
    path('class/<int:class_pk>/delete/', views.class_member_delete_view, name='delete-class-members'),
]

book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/', views.ListBookView.as_view(), name='list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name='detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name='create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update-book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review'),
    path('savebook/', views.savebook_list_view, name='list-savebook'),
    path('savebook/append/', views.savebook_append, name='append-savebook'),
    path('savebook/orderchange/', views.savebook_orderchange_view, name='orderchange-savebook'),
    path('savebook/delete/', views.bookorder_delete, name='delete-savebook'),
    path('like_for_book/', views.like_for_book, name='like_for_book'), 
]

bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>{% block title %}本棚アプリ{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-success sticky-top">
      <div class="navbar-nav d-flex flex-row">
        <a class="nav-link mx-3" href="{% url 'list-book' %}">書籍一覧</a>
        <a class="nav-link mx-3" href="{% url 'create-book' %}">書籍登録</a>
        {% if request.user.is_authenticated %}
          <a class="nav-link mx-3" href="{% url 'list-savebook' %}">保存した書籍一覧</a>
          <a class="nav-link mx-3" href="{% url 'accounts:class-list' %}">クラス一覧</a>
        {% endif %}
      </div>
      <div class="navbar-nav d-flex flex-row">
        {% if request.user.is_authenticated %}
          <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
          <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
          <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
        {% endif %}
      </div>
    </nav>
    <div class="p-4">
      <h1>{% block h1 %}{% endblock %}</h1>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>