book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/', views.ListBookView.as_view(), name='list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name='detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name='create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update-book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review'),
    path('savebook/', views.savebook_list_view, name='list-savebook'),
    path('savebook/append/', views.savebook_append, name='append-savebook'),
    path('savebook/orderchange/', views.savebook_orderchange_view, name='orderchange-savebook'),
    path('savebook/delete/', views.bookorder_delete, name='delete-savebook'),
    path('like_for_book/', views.like_for_book, name='like_for_book'), 
]

bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from .consts import MAX_RATE
from django.contrib.auth.models import User
from django.utils import timezone
from django_mysql.models import ListTextField

RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE + 1)]

CATEGORY = (('business', 'ビジネス'), ('life','生活'), ('other','その他'))
class Book(models.Model):
    title = models.CharField(max_length = 100)
    text = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True)
    category = models.CharField(
        max_length = 100,
        choices = CATEGORY
    )
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '本のデータ'

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

# ----------投稿に対するいいね----------
class LikeForBook(models.Model):
    """投稿に対するいいね"""
    target = models.ForeignKey(Book, on_delete=models.CASCADE) # いいね対象書籍
    user = models.ForeignKey(User, on_delete=models.CASCADE) # いいねしたUser
    timestamp = models.DateTimeField(default=timezone.now) # いいねしたタイミング
# ----------

release_choice = ((True, '公開'),(False, '非公開'))
class Folder(models.Model):
    title = models.CharField(max_length=100)
    release = models.BooleanField(choices=release_choice)
    # ----------編成情報を詰め込んでいくリスト----------
    post_list = ListTextField(
        base_field=models.IntegerField(), # これで数値型で管理できるようになる？
        size=100,  # Maximum of 100 ids in list(要素数は100個まで？)
        )
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

# @receiver(post_delete,sender=Memo)#postがdeleteされたらdelete_mypostが実行される
# def delete_mypost(sender,instance,**kwargs):
#     profile1 = Profile.objects.get(pk=instance.user.id)
#     profile1.mypost1.remove(str(instance.pk))
#     profile1.save()


# @receiver(post_save,sender=Memo)
# def append_mypost(sender,instance,created,**kwargs):
#     profile1 = Profile.objects.get(pk=instance.user.id)
#     if created:
#         profile1.mypost1.insert(0,str(instance.pk))
#     profile1.save()

book/forms.py
from django import forms

class SearchForm(forms.Form):
        keyword = forms.CharField(label='検索', max_length=100)

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)
from .models import Book, Review, LikeForBook
from django.db.models import Avg

from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE

from .forms import SearchForm #-----検索機能

import time

import sys
sys.path.append('../')
from accounts.models import Profile

from django.http import JsonResponse
from django.shortcuts import get_object_or_404

class ListBookView(LoginRequiredMixin, ListView):
    template_name = 'book/book_list.html'
    model = Book
    paginate_by = ITEM_PER_PAGE

class DetailBookView(LoginRequiredMixin, DetailView):
    template_name = 'book/book_detail.html'
    model = Book
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        like_for_book_count = self.object.likeforbook_set.count()
        # ポストに対するイイね数
        context['like_for_book_count'] = like_for_book_count
        # ログイン中のユーザーがイイねしているかどうか
        if self.object.likeforbook_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_book'] = True
        else:
            context['is_user_liked_for_book'] = False
        return context

def like_for_book(request):
    book_pk = request.POST.get('book_pk')
    context = {
        'user': f'{request.user.last_name} {request.user.first_name}',
    }
    book = get_object_or_404(Book, pk=book_pk)
    like = LikeForBook.objects.filter(target=book, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(target=book, user=request.user)
        context['method'] = 'create'

    context['like_for_book_count'] = book.likeforbook_set.count()

    return JsonResponse(context)

class CreateBookView(LoginRequiredMixin, CreateView):
    template_name = 'book/book_create.html'
    model = Book
    fields = ('title', 'text', 'category', 'thumbnail')
    success_url = reverse_lazy('list-book')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

class DeleteBookView(LoginRequiredMixin, DeleteView):
    template_name = 'book/book_confirm_delete.html'
    model = Book
    success_url = reverse_lazy('list-book')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj

class UpdateBookView(LoginRequiredMixin, UpdateView):
    template_name = 'book/book_update.html'
    model = Book
    fields = ('title', 'text', 'category', 'thumbnail')
    success_url = reverse_lazy('list-book')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

def index_view(request):
    #-----↓検索機能で追加したやつ↓-----
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid(): # 正常な値が入力されていれば
        keyword = searchForm.cleaned_data['keyword'] #入力された値をKeywordに代入
        books = Book.objects.filter(title__contains=keyword)
    else:
        searchForm = SearchForm()
        books = Book.objects.all()
    books = books.order_by('-id')
    #-----↑検索機能で追加したやつ↑-----
    ranking_list = Book.objects.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')
    paginator = Paginator(ranking_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.page(page_number)
    context = {
        'ranking_list': ranking_list,
        'page_obj': page_obj,
        #booksとsearchFormは検索機能用
        'books': books,
        'searchForm': searchForm,
    }
    return render(
        request,
        'book/index.html',
        context
        ) 

class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    fields = ('book', 'title', 'text', 'rate')
    template_name = 'book/review_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Book.objects.get(pk=self.kwargs['book_id'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail-book', kwargs={'pk': self.object.book.id})


def savebook_list_view(request):
    object_list = Book.objects.all()
    profile1 = Profile.objects.get(pk=request.user.id) # profile1に一人分のプロフィールデータが入る
    save_book_id = profile1.save_book_id # profile1の本の並び順をidで取得する
    print(f'保存された書籍データのid:{save_book_id}')
    # ----------↓設定されている順番に並び替える↓----------
    books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
    sorted_books = [books_dict[int(id)] for id in save_book_id] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
    print(f"並び替えられた書籍データ:{sorted_books}")
    # ----------↑設定されている順番に並び替える↑----------
    return render(
    request,
    'book/book_save_list.html',
    {"object_list": object_list, "sorted_books": sorted_books}
    )

def savebook_orderchange_view(request):
    # ----------↓object_listに全書籍データを代入↓----------
    object_list = Book.objects.all()
    # ----------↓profile1にログインしているユーザーのプロフィール情報を代入↓----------
    profile1 = Profile.objects.get(pk=request.user.id) # profile1に一人分のプロフィールデータが入る
    # ----------↓profile1の本の並び順を取得する↓----------
    order_list = profile1.save_book_id
    object_pk_list = []
    for obj in object_list:
        object_pk_list.append(obj.pk)
    # print(f"全書籍のid(object_pk_list):{object_pk_list}")
    # print(f"ユーザーの並び変え順(order_list):{order_list}")
    # ----------↓設定されている順番に並び替える↓----------
    books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
    sorted_books_list = [books_dict[int(id)] for id in order_list] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
    # print(f"idとデータの辞書(book_dict):{books_dict}")
    print(f"並び替えられた書籍データ（sorted_books_list）:{sorted_books_list}")
    # ----------↑設定されている順番に並び替える↑----------
    # ----------↓並び替え確定のボタンが押されてリクエストが来た時の分岐↓----------
    if (request.method == 'POST'):
        new_order = request.POST['submit'].split(",") # new_orderに並び替えた後のデータをリスト型で保管する
        print(new_order)
        # print(f"html側から受け取ったもの：{new_order}") # htmlから渡されたものを確認する
        profile1.save_book_id = new_order # プロフィールのsave_book_idに上書き
        profile1.save() # 変更を保存
        print(f"並び替え後のlist：{profile1.save_book_id}") # profileテーブルの内容が上書きされているかを確認する
        return redirect('list-savebook')
    # ----------↑並び替え確定のボタンが押されてリクエストが来た時の分岐↑----------
    # ----------↓並び替えするためにリクエストが来た時の分岐↓----------
    else:
        context = {
            "object_list": object_list, # 全書籍データ
            "object_pk_list": object_pk_list, # 全書籍データ（idのみ）
            "order_list": order_list, # ユーザーの並び替え順（idのみ）
            "books_dict": books_dict, # {id: その書籍データ}と、辞書型で全書籍データがある
            "sorted_books_list": sorted_books_list, # 並び替え順で書籍データが詰まっている（リスト型）
        }
        return render(
        request,
        'book/order_change.html',
        context)
    # ----------↑並び替えするためにリクエストが来た時の分岐↑----------

def savebook_append(request):
    object_list = Book.objects.all()
    profile1 = Profile.objects.get(pk=request.user.id)
    # ----------追加ボタンが押された分岐----------
    if request.method == 'POST':
        append_book = request.POST.getlist('office')
        for book_id in append_book:
            profile1.save_book_id.append(book_id)
        profile1.save()
        return redirect('list-savebook')
    # ----------
    else:
        # ----------↓obj_li_pkに全書籍のidを詰め込む↓----------
        obj_li_pk = []
        for obj in object_list:
            obj_li_pk.append(obj.id)
        # ----------
        # ----------↓obj_li_pkの中から、既に保存している書籍は削除する↓----------
        for item in profile1.save_book_id:
            obj_li_pk.remove(int(item))
        print(f'{profile1.user}の保存していない書籍番号:{obj_li_pk}')
        books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
        nosave_books_list = [books_dict[int(id)] for id in obj_li_pk] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
        # ----------↑obj_li_pkの中から、既に保存している書籍は削除する↑----------
        return render(
            request,
            'book/savebook_append.html',
            {'nosave_books_list': nosave_books_list} # 表示する書籍データがリスト形で詰まっている
    )

def bookorder_delete(request):
    profile1 = Profile.objects.get(pk = request.user.id)
    # ----------削除ボタンが押された分岐----------
    if request.method == 'POST':
        delete_book = request.POST.getlist('office')
        for book_id in delete_book:
            profile1.save_book_id.remove(book_id)
        profile1.save()
        return redirect('list-savebook')
    # ----------
    # ----------削除画面にアクセスする----------
    else:
        object_list = Book.objects.all()
        save_book_id = profile1.save_book_id # profile1の本の並び順をidで取得する
        print(f'保存された書籍データのid:{save_book_id}')
        # ----------↓設定されている順番に並び替える↓----------
        books_dict = dict([(book.id, book) for book in object_list]) # [id: そのidのBookデータ]という形で辞書に収める
        sorted_books = [books_dict[int(id)] for id in save_book_id] # 表示したい並び順でidの入っているリストで繰り返し処理して、その本情報をsorted_booksに積めていく
        print(f"並び替えられた書籍データ:{sorted_books}")
        # ----------↑設定されている順番に並び替える↑----------
        return render(request, 'book/savebook_delete.html',
        {
            'sorted_books': sorted_books,
        })

book/templates/book/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}書籍削除{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">{{ object.title }}を削除する</button>
    </form>
{% endblock %}

book/templates/book/book_create.html
{% extends 'base.html' %}

{% block title %}書籍作成{% endblock title %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="作成する">
    </form>
{% endblock content %}

book/templates/book/book_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.title }}{% endblock %}
{% block h1 %}書籍詳細{% endblock %}
{% block content %}
    <div class="card-header">
        {% if is_user_liked_for_book %}
        <button type="button" id="ajax-like-for-book" style="border:none;background:none">
        <!-- すでにイイねしている時はfasクラス -->
        <i class="fas fa-heart text-danger" id="like-for-book-icon"></i>
        </button>
        {% else %}
        <button type="button" id="ajax-like-for-book" class="ajax-like-for-book" style="border:none;background:none">
        <!-- イイねしていないときはfarクラス -->
        <i class="far fa-heart text-danger" id="like-for-book-icon"></i>
        </button>
        {% endif %}
        <!-- イイねの数 -->
        <span id="like-for-book-count">{{ like_for_book_count }}</span>
        <span>件のイイね</span>
    </div>
    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-success">{{ object.title }}</h2>
            <p>{{ object.text }}</p>
            <div class="border p-4 mb-2">
                {% for review in object.review_set.all %}
                <div>
                    <h3 class="h4">{{ review.title }}</h3>
                    <div class="px-2">
                        <span>(投稿ユーザー： {{ review.user.username }})</span>
                        <h6>評価：{{ review.rate }}点</h6>
                        <p>{{ review.text }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <a href="{% url 'list-book' %}" class="btn btn-primary">一覧へ</a>
            <a href="{% url 'review' object.pk %}" class="btn btn-primary">レビューする</a>
            <a href="{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a>
            <a href="{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a>
            <h6 class="card-title">{{ object.category }}</h6>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.js"></script>
    <script type="text/javascript">
        var likeBookButtons = document.getElementsByClassName("ajax-like-for-book");
        console.log(likeBookButtons)
        /* ポストに対するイイね */
        document.getElementById('ajax-like-for-book').addEventListener('click', e => {
          e.preventDefault();
          const url = '{% url "like_for_book" %}';
            fetch(url, {
            method: 'POST',
            body: `book_pk={{book.pk}}`,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': '{{ csrf_token }}',
            },
          }).then(response => {
            return response.json();
          }).then(response => {
            // イイね数を書き換える
            const counter = document.getElementById('like-for-book-count')
            counter.textContent = response.like_for_book_count
            const icon = document.getElementById('like-for-book-icon')
            // 作成した場合はハートを塗る
            if (response.method == 'create') {
              icon.classList.remove('far')
              icon.classList.add('fas')
              icon.id = 'like-for-book-icon'
            } else {
              icon.classList.remove('fas')
              icon.classList.add('far')
              icon.id = 'like-for-book-icon'
            }
          }).catch(error => {
            console.log(error);
          });
        });
      </script>
{% endblock content %}

book/templates/book/book_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}書籍一覧{% endblock title %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
    <div id="listWithHandle">
        {% for item in object_list %}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h2 class="text-success">{{ item.title }}</h2>
                <h6>カテゴリ：{{ item.category }}</h6>
                <div class="mt-3">
                    <a href="{% url 'detail-book' item.pk %}">詳細へ</a>
                </div>
            </div>
        {% endfor %}
    </div>
<script src="../../static/book/js/Sortable.min.js"></script>
<script>
    $(function(){
        Sortable.create(listWithHandle);
    });
</script>
    {% include 'book/components/pagination.html' %}
    
{% endblock content %}

book/templates/book/book_save_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}保存書籍一覧{% endblock title %}
{% block h1 %}保存書籍一覧{% endblock %}

{% block content %}
<a href="{% url 'orderchange-savebook' %}" class="btn btn-success mt-4">並び替える</a>
<a href="{% url 'append-savebook' %}" class="btn btn-success mt-4">保存書籍を追加する</a>
<a href="{% url 'delete-savebook' %}" class="btn btn-success mt-4">保存書籍を削除する</a>
{% for book in sorted_books %}
    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-success">{{ book.title }}</h2>
        {% if book.thumbnail %}
            <img src="{{ book.thumbnail.url }}" class="img-thumbnail"/>
        {% endif %}
        <h6>カテゴリ：{{ book.category }}</h6>
        <div class="mt-3">
            <a href="{% url 'detail-book' book.pk %}" class="btn btn-primary">詳細</a>
        </div>
    </div>
{% endfor %}
{% endblock content %}

book/templates/book/book_update.html
{% extends 'base.html' %}

{% block title %}書籍修正{% endblock %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{{ object.title }}修正する</button>
    </form>
{% endblock %}

book/templates/book/bookorder_append.html
{% extends 'base.html' %}
{% load static %}

{% block title %}書籍一覧{% endblock title %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
<form method='post' class='form' name="form">{% csrf_token %}
{% for book in display_books_list %}
<div class="p-4 m-4 bg-light border border-success rounded">
    <h2 class="text-success">{{ book.title }}</h2>
    {% if book.thumbnail %}
        <img src="{{ book.thumbnail.url }}" class="img-thumbnail"/>
    {% endif %}
    <h6>カテゴリ：{{ book.category }}</h6>
    <div class="mt-3">
        <label><input type="checkbox" name="office" value="{{ book.id }}">追加する</label>
    </div>
</div>
{% endfor %}
<input type="hidden" name='submit' value="送信">
<button type="submit" class="btn btn-success mt-4">決定</button>
</form>
{% endblock content %}

book/templates/book/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}本棚アプリ{% endblock %}
{% block h1 %}本棚アプリ{% endblock %}

{% block content %}
<!-- <script src="{% static 'book/js/script.js' %}"></script>
<button type="button" onclick="hello()">hello関数呼び出し</button> -->
{% if searchForm %}
    <form action='{% url "index" %}' method='get'>
        <div class='form-group'>
            {{ searchForm }}
            <input type="submit" class="btn btn-outline-primary" value="OK" />
            <a href="{% url 'index' %}" class="btn btn-outline-secondary">クリア</a>
        </div>
    </form>
{% endif %}
<div class="row">
    <div class="col-9">
    {% for book in books %}
    <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-success">{{ book.title }}</h2>
        {% if book.thumbnail %} <!-- shumbnailは存在している場合だけ表示する（このif文を記載しないとshumbnailがない場合エラーになる） -->
            <img src="{{ book.thumbnail.url }}" class="img-thumbnail" /> 
        {% endif %}
        <h6>カテゴリ：{{ book.category }}</h6>
        <div class="mt-3">
            <a href="{% url 'detail-book' book.pk %}">詳細</a>
        </div>
    </div>
    {% endfor %}
    </div>
    <div class="col-3">
        <h2>評価順TOP2</h2>
        {% for ranking_book in page_obj %}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h3 class="text-success h5">{{ ranking_book.title }}</h3>
            {% if ranking_book.thumbnail %} <!-- shumbnailは存在している場合だけ表示する（このif文を記載しないとshumbnailがない場合エラーになる） -->
                <img src="{{ ranking_book.thumbnail.url }}" cl+ass="img-thumbnail" />
            {% endif %}
            <h6>評価：{{ ranking_book.avg_rating|floatformat:2 }}点</h6>
            <a href="{% url 'detail-book' ranking_book.id %}">詳細を見る</a>
        </div>
        {% endfor %}
        {% include 'book/components/pagination.html' %}
    </div>
</div>
{% endblock content %}

book/templates/book/order_change.html
{% extends 'base.html' %}
{% load static %}

{% block title %}書籍一覧{% endblock title %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
    <form method='post' class='form' name="form">{% csrf_token %}
        <div id="listWithHandle" class="list-group">
            {% for book in sorted_books_list %}
            <div class="wrap list-group-item" data-name="{{ book.id }}">
                <div class="d-flex">
                    <h2 class="text-success align-self-center aaa">{{ book.title }}</h2>
                    {% if book.thumbnail %}
                        <img src="{{ book.thumbnail.url }}" height="200"/>
                    {% endif %}
                </div>
                <h6>カテゴリ：{{ book.category }}</h6>
            </div>
            {% endfor %}
        </div>
    <input type="hidden" name='submit' value="">
    <button type="submit" class="btn btn-success mt-4" onclick="return_sort()">決定する</button>
    </form>
    {{ object_pk_list|json_script:"object_pk_list" }} <!-- viewsから渡された変数『object_list（左辺）』をscript側でobject_list（右辺）として使用 -->
    {{ order_list|json_script:"order_list" }} <!-- viewsから渡された変数『order_list（左辺）』をscript側でorder_list（右辺）として使用 -->
<script src="{% static 'accounts/js/Sortable.min.js' %}"></script>
<script src="{% static 'accounts/js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'accounts/js/jquery.cookie.1.4.1.min.js' %}"></script>
<script>
    var object_pk_list = JSON.parse(document.getElementById('object_pk_list').textContent); //viewsから渡された変数『object_pk_list（右辺）』をobject_pk_list（左辺）として定義（これが表示する対象のリスト）
    var order_list = JSON.parse(document.getElementById('order_list').textContent); //viewsから渡された変数『order_list（右辺）』をorder_list（左辺）として定義（これが表示する対象のリスト）
    // console.log(`profileのbookorder：${order_list}`)
    var page; // ここに表示するデータを代入するための変数
    var table = []; // viewsから渡された引数が空だった場合に参照するリスト
    for (i = 0; i < object_pk_list.length; i++) {
        console.log(object_pk_list[i]);
        table[i] = object_pk_list[i];
    }
    console.log(`デフォルト設定${table}`)


    function init() {
        sort_table = getTable();


    }

    function getTable() {
        page = order_list; //order_list_を一旦『page』に代入
        var sort_table;
        console.log(`page:${page}`)
        if(page.length !== 0) { //並び替えが登録されている場合はその並び順で表示する 
            console.log("ifに引っかかった。profileのリストを参照")
            // console.log(`order_list：${order_list}`)
            sort_table = order_list;
            // console.log(`sort_table：${sort_table}`)
        } 
        else{ // 並び替えが登録されていない場合は、デフォルトの順番で表示する
            console.log("elseに引っかかった。デフォルト設定を参照")
            sort_table = table;
        }
        console.log(`sort_table:${sort_table}`)
        return sort_table;
    }


    var return_sort = function(){
        console.log("return_sort実行")
        var box = [];
            $('.wrap').each(function(index, element){
            box.push($(element).data('name'));
            });
        console.log(box)
        document.form.submit.value = box;
    }

    $(function(){
        init();
        Sortable.create(listWithHandle, {
        animation: 150,
        onUpdate: function (e) {
            var box = [];
            $('.wrap').each(function(index, element){
            box.push($(element).data('name'));
            });
            order_list = box
            console.log(order_list);
            },
      });
    });
</script>


    
{% endblock content %}

book/templates/book/review_form.html
{% extends 'base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}
{% block content %}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        <label>
            対象書籍
        </label>
        <input class="form-control" value="{{ book.title }}" readonly>
        <label>
            タイトル
        </label>
        <input class="form-control" name="title">
        <label>
            本文
        </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <label>
            星の数
        </label>
        <select class="form-control" name="rate">
            <option value="0">0（最低）</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3（普通）</option>
            <option value="4">4</option>
            <option value="5">5（最高）</option>
        </select>
        <input type="hidden" name='book' value="{{ book.id }}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    </form>
{% endblock %}